### PR TITLE
[Feature] Add overview page

### LINKED ISSUE #14: Implement basic overview UI for BoopChat
image

### PR DESCRIPTION
**Pull request by JChris246**
### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/BoopChat/boop/pulls) the bugtracker for similar pull requests
- [x] I have performed a self-review of my own code

### What is the purpose of your *pull request*?
- [x] New feature (non-breaking change which adds functionality)

### Description of your *pull request* and other information
This PR is to add the basic template for the UI of the overview page. It consists of the sidebar which gives info on the logged in user as well as navigates between contacts, chats (list) and settings. There is also a section reserved for chatting. Closes #14 .

## Screenshots (if appropriate):

image
image
image

### CODE REVIEW

**Comment by davidfowl** [comment]
Looks nice!

**Comment by davidfowl** [comment]
Is this just the chats screen? Does it have the conversation list and contact list?

**Review by D-Garnes — APPROVED** [review]
looks good.

**Comment by JChris246** [comment]
The panel on the right (white) is the result of clicking on a chat from the chat list (grey panel) if any exist; it should be blank initially. The middle panel (grey) would change based on the tab selected from the side panel on the left (black). So the white panel only ever contains chats and the grey panel would be the lists (chats, contacts, and settings)

**Pull request merged**
