### PR TITLE
Added Boop ERD concept

### PR DESCRIPTION
**Pull request by krazeelazy**
Added the initial ERD concept based on our first discussion.

### CODE REVIEW

**Comment by davidfowl** [comment]
Can you convert this to an svg file?

**Comment by krazeelazy** [comment]
It's now a drawio.svg file so we can continue editing it using draw.io.

**Comment by davidfowl** [comment]
@JChris246 does this have the changes that would be required for when we eventually implement group chat?

**Comment by JChris246** [comment]
> @JChris246 does this have the changes that would be required for when we eventually implement group chat?

I suggest adding a 'Participants' table to allow for tracking of 2+ users of a conversation as well as renaming the table fields to better identify FKs.

image

**Comment by krazeelazy** [comment]
I redid the ERD with the suggestions. I also renamed the messages timestamp to sent_at so the name's more meaningful. We should do the same for the users timestamp.

**Comment by JChris246** [comment]
> I redid the ERD with the suggestions. I also renamed the messages timestamp to sent_at so the name's more meaningful. We should do the same for the users timestamp.

Remind me, what does the timestamp in the user refer to, is it the date the user created their account?

**Comment by krazeelazy** [comment]
> > I redid the ERD with the suggestions. I also renamed the messages timestamp to sent_at so the name's more meaningful. We should do the same for the users timestamp.
> 
> Remind me, what does the timestamp in the user refer to, is it the date the user created their account?

Wasn't it being used to track activity status?
This is part of the design we started with:
Screen Shot 2021-08-23 at 1 57 52 PM
It's being used in the Join function that is called when the user starts a session.

**Comment by JChris246** [comment]
> > > I redid the ERD with the suggestions. I also renamed the messages timestamp to sent_at so the name's more meaningful. We should do the same for the users timestamp.
> > 
> > 
> > Remind me, what does the timestamp in the user refer to, is it the date the user created their account?
> 
> Wasn't it being used to track activity status?
> This is part of the design we started with:
> Screen Shot 2021-08-23 at 1 57 52 PM
> It's being used in the Join function that is called when the user starts a session.

Ahh, so call last_active then?

**Comment by krazeelazy** [comment]
> > > > I redid the ERD with the suggestions. I also renamed the messages timestamp to sent_at so the name's more meaningful. We should do the same for the users timestamp.
> > > 
> > > 
> > > Remind me, what does the timestamp in the user refer to, is it the date the user created their account?
> > 
> > 
> > Wasn't it being used to track activity status?
> > This is part of the design we started with:
> > Screen Shot 2021-08-23 at 1 57 52 PM
> > It's being used in the Join function that is called when the user starts a session.
> 
> Ahh, so call last_active then?
Made the change:
boop_db drawio

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
