### PR TITLE
feat: replace sample contacts with request to server

### PR DESCRIPTION
**Pull request by JChris246**
### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/BoopChat/boop/pulls) the bugtracker for similar pull requests
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Covered the code with tests that prove my fix is effective or that my feature works (note that PRs
without tests will be REJECTED)
- [x] New and existing unit tests pass locally with my changes

---

### What is the purpose of your *pull request*?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains
the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much
context and examples as possible.

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by krazeelazy** [comment]
I got this error page after adding a new contact:

Screen Shot 2021-09-13 at 11 41 25 AM

Reloading the page shows that the new contact (last 1) was added to the list but the image is not being displayed:

Screen Shot 2021-09-13 at 11 42 58 AM

**Comment by krazeelazy** [comment]
> I got this error page after adding a new contact:
> 
> Screen Shot 2021-09-13 at 11 41 25 AM
> 
> Reloading the page shows that the new contact (last 1) was added to the list but the image is not being displayed:
> 
> Screen Shot 2021-09-13 at 11 42 58 AM

The error is in the controller. It returns the contact association:
  `"contact": {
      "createdAt",
      "updatedAt",
      "user_id",
      "contact_id",
    }`

Instead of the new contact's user details.

**Comment by krazeelazy** [comment]
> > I got this error page after adding a new contact:
> > Screen Shot 2021-09-13 at 11 41 25 AM
> > Reloading the page shows that the new contact (last 1) was added to the list but the image is not being displayed:
> > Screen Shot 2021-09-13 at 11 42 58 AM
> 
> The error is in the controller. It returns the contact association:
> `"contact": { "createdAt", "updatedAt", "user_id", "contact_id" }`
> 
> Instead of the new contact's user details.

working on a fix for this now.

**Comment by krazeelazy** [comment]
The changes work:
Screen Shot 2021-09-13 at 12 23 29 PM

**Review by krazeelazy — APPROVED** [review]
- Changes look good and work. 
- Once the api is overhauled (var names change from snake case to upper camel case) some changes will have to be done when retrieving the values from the response in client/src/components/messenger/Contacts.js.

**Comment by JChris246** [comment]
>     * Changes look good and work.
> 
>     * Once the api is overhauled (var names change from snake case to upper camel case) some changes will have to be done when retrieving the values from the response in client/src/components/messenger/Contacts.js.

Okay np

**Pull request merged**
