### PR TITLE
Init React App

### PR DESCRIPTION
**Pull request by JChris246**
Initialize React app in project

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]
LGTM (Looks good to me)

**Comment by davidfowl** [comment]
Wait one, second, this should probably be in another folder. We probably need a client and server folder.

**Comment by JChris246** [comment]
> Wait one, second, this should probably be in another folder. We probably need a client and server folder.

yeah this actually crossed my mind after making the PR 😅

**Review by davidfowl — APPROVED** [review]
Looks good now.

**Pull request merged**
